/*
Navicat MySQL Data Transfer

Source Server         : newcrawler
Source Server Version : 50169
Source Host           : localhost:3306
Source Database       : newcrawler-amazon

Target Server Type    : MYSQL
Target Server Version : 50169
File Encoding         : 65001

Date: 2013-10-21 20:44:59
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for CRAWLER_BACKUPTABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_BACKUPTABLE`;
CREATE TABLE `CRAWLER_BACKUPTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDATE` datetime DEFAULT NULL,
  `FILENAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `REMARK` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `SITEID` bigint(20) DEFAULT NULL,
  `STATUS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_CRAWLBOTTABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_CRAWLBOTTABLE`;
CREATE TABLE `CRAWLER_CRAWLBOTTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDATE` datetime DEFAULT NULL,
  `PROJECT` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `RATE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `STATUS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  `URL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `VER` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_CRAWLDATATABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_CRAWLDATATABLE`;
CREATE TABLE `CRAWLER_CRAWLDATATABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRAWLURL` varchar(1500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `CREATEDATE` datetime DEFAULT NULL,
  `DATA` mediumblob,
  `DEPLOYDATE` datetime DEFAULT NULL,
  `MD5DIGEST` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `SITEID` bigint(20) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_siteid` (`SITEID`,`CREATEDATE`),
  KEY `idx_md5digest` (`SITEID`,`MD5DIGEST`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1877188 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_CRAWLINFOCACHETABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_CRAWLINFOCACHETABLE`;
CREATE TABLE `CRAWLER_CRAWLINFOCACHETABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRAWLDATAFORM` mediumblob,
  `CREATEDATE` datetime DEFAULT NULL,
  `MD5DIGEST` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `SITEID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_CRAWLURLTABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_CRAWLURLTABLE`;
CREATE TABLE `CRAWLER_CRAWLURLTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDATE` datetime DEFAULT NULL,
  `SITEID` bigint(20) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  `URL` varchar(1500) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_siteid` (`SITEID`,`CREATEDATE`),
  KEY `idx_status` (`SITEID`,`STATUS`,`ID`) USING BTREE,
  KEY `idx_url` (`SITEID`,`URL`(255))
) ENGINE=InnoDB AUTO_INCREMENT=253542 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_DATARULESTABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_DATARULESTABLE`;
CREATE TABLE `CRAWLER_DATARULESTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ABSOLUTEURLBASE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ABSOLUTEURLREGEX` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `CANTCONTAINTEXT` mediumblob,
  `CONVERTENCODE` mediumblob,
  `DEFAULTVALUE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ENDSTRING` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `EXCLUDEHTMLTAGS` mediumblob,
  `EXCLUDETEXT` mediumblob,
  `FILESAVEPLUGINID` bigint(20) DEFAULT NULL,
  `FILESAVEPLUGINREGEX` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `FILESAVESUBDIR` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `FILTERINTERID` bigint(20) DEFAULT NULL,
  `FILTERPLUGINID` bigint(20) DEFAULT NULL,
  `FILTERSORT` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `FUNCTIONEXPRESSION` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `INDEX` int(11) DEFAULT NULL,
  `ISABSOLUTE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISCANTNULL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISCONVERTENCODING` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISDEFAULTVALUE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISDOWNLOAD` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISFROMLABEL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISLOOP` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISNESTED` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISOFFSET` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISPUBLIC` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISREGEXCANTCONTAINTEXT` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISREGEXEXCLUDETEXT` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISREGEXMUSTCONTAINTEXT` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISREGEXREPLACETEXT` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISSTARTPOSITION` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISTEMP` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISURL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `LABELCOMBINATION` varchar(800) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `LABELTYPE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `MERGERULES` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `MUSTCONTAINTEXT` mediumblob,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `NESTEDSITEID` bigint(20) DEFAULT NULL,
  `REGEXFILTER` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `REPLACETEXT` mediumblob,
  `SEARCHMODE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `SEARCHREGEX` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `SITEID` bigint(20) DEFAULT NULL,
  `STARTSTRING` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `TEXTLEN` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `VALUEFROMLABEL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `XPATH` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISDATAORIGIN` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `DATAORIGIN` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `JAVASCRIPTFILTER` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_DEPLOYTABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_DEPLOYTABLE`;
CREATE TABLE `CRAWLER_DEPLOYTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DEPLOYPARAMS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `DEPLOYPLUGINID` bigint(20) DEFAULT NULL,
  `DEPLOYURL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `EMAILNOTICEID` bigint(20) DEFAULT NULL,
  `FILESAVEPLUGINID` bigint(20) DEFAULT NULL,
  `FILESAVEPLUGINREGEX` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `FILESAVESUBDIR` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `HTTPREQUESTID` bigint(20) DEFAULT NULL,
  `IMAGELABELS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISUPLOADIMAGE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `LABELBYURL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `LASTDEPLOYTIME` datetime DEFAULT NULL,
  `MESSAGE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `SITEID` bigint(20) DEFAULT NULL,
  `SITEIDBYURL` bigint(20) DEFAULT NULL,
  `STATUS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `UPDATESTATUS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `WHEN` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `WHERE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_EMAILNOTICETABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_EMAILNOTICETABLE`;
CREATE TABLE `CRAWLER_EMAILNOTICETABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDATE` datetime DEFAULT NULL,
  `ISATTACHMENT` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `TEMPCONTENT` mediumblob,
  `TEMPTITLE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `TOEMAIL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_HTTPINTERTABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_HTTPINTERTABLE`;
CREATE TABLE `CRAWLER_HTTPINTERTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDATE` datetime DEFAULT NULL,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `TYPE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  `URL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_HTTPREQUESTTABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_HTTPREQUESTTABLE`;
CREATE TABLE `CRAWLER_HTTPREQUESTTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COOKIE` mediumblob,
  `COOKIEGETMETHOD` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `CREATEDATE` datetime DEFAULT NULL,
  `ENCODING` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `HEADERS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `LOGINCHECK` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `LOGINCODE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `LOGINCODEURL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `LOGINENCODING` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `LOGINHEADERS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `LOGINMETHOD` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `LOGINURL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `LOGINURLPARAMS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `METHOD` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `TIMEOUT` int(11) DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  `USERAGENT` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `UUID` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_PLUGINCACHETABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_PLUGINCACHETABLE`;
CREATE TABLE `CRAWLER_PLUGINCACHETABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDATE` datetime DEFAULT NULL,
  `DATACACHE` mediumblob,
  `JARURL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_PLUGINCONFIGTABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_PLUGINCONFIGTABLE`;
CREATE TABLE `CRAWLER_PLUGINCONFIGTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDATE` datetime DEFAULT NULL,
  `MAINCLASS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `PLUGINURL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `PROPERTIES` mediumblob,
  `TYPE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_PLUGINTABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_PLUGINTABLE`;
CREATE TABLE `CRAWLER_PLUGINTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDATE` datetime DEFAULT NULL,
  `FILENAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `MAINCLASS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `PLATFORM` mediumblob,
  `PROPERTIES` mediumblob,
  `STATUS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `TYPE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_SCHEDULETABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_SCHEDULETABLE`;
CREATE TABLE `CRAWLER_SCHEDULETABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDATE` datetime DEFAULT NULL,
  `DESC` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `LASTTIME` datetime DEFAULT NULL,
  `SCHEDULETIME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `SITEID` bigint(20) DEFAULT NULL,
  `STATUS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `TASKNAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `TYPE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_SITETABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_SITETABLE`;
CREATE TABLE `CRAWLER_SITETABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `AREAENDSTRING` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `AREASTARTSTRING` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `CACHEMD5DIGEST` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `CRAWLNUMLIMIT` int(11) DEFAULT NULL,
  `CREATEDATE` datetime DEFAULT NULL,
  `DEPLOYQUEUENAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `DESC` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ENCODING` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `EXPIREDDAYSDATA` int(11) DEFAULT NULL,
  `EXPIREDDAYSURL` int(11) DEFAULT NULL,
  `HTTPREQUESTID` bigint(20) DEFAULT NULL,
  `ISAUTO` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISLOOP` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISMERGE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISNOTSAVEDATA` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISNOTSAVEURL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISREALTIMECRAWL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISREPEAT` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISREPEATDATA` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISREVERSE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISSPIDERFILTER` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `MAXSIZE` int(11) DEFAULT NULL,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `QUEUENAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `RETURNDATALEN` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  `URL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `URLCHECKREGEX` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `URLFETCHPLUGINID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_URLCHECKRESULTTABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_URLCHECKRESULTTABLE`;
CREATE TABLE `CRAWLER_URLCHECKRESULTTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDATE` datetime DEFAULT NULL,
  `RESULT` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `SITEID` bigint(20) DEFAULT NULL,
  `TIMES` bigint(20) DEFAULT NULL,
  `URL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for CRAWLER_URLCHECKTABLE
-- ----------------------------
DROP TABLE IF EXISTS `CRAWLER_URLCHECKTABLE`;
CREATE TABLE `CRAWLER_URLCHECKTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CHECKDIGEST` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `CREATEDATE` datetime DEFAULT NULL,
  `EMAILNOTICEID` bigint(20) DEFAULT NULL,
  `HTTPREQUESTID` bigint(20) DEFAULT NULL,
  `ISEMAILNOTICE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISPING` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ISSAVE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `SITEID` bigint(20) DEFAULT NULL,
  `STATUS` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  `URL` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for FILECHUNKENTITY
-- ----------------------------
DROP TABLE IF EXISTS `FILECHUNKENTITY`;
CREATE TABLE `FILECHUNKENTITY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BLOB` mediumblob,
  `FILEID` bigint(20) DEFAULT NULL,
  `INDEX` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for FILEENTITY
-- ----------------------------
DROP TABLE IF EXISTS `FILEENTITY`;
CREATE TABLE `FILEENTITY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FILENAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `FOLDERID` bigint(20) DEFAULT NULL,
  `LASTMODIFIEDTIME` datetime DEFAULT NULL,
  `MIMETYPE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `SIZE` int(11) DEFAULT NULL,
  `TITLE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for FOLDERENTITY
-- ----------------------------
DROP TABLE IF EXISTS `FOLDERENTITY`;
CREATE TABLE `FOLDERENTITY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FULLNAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `PARENTNAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for QUEUETASKTABLE
-- ----------------------------
DROP TABLE IF EXISTS `QUEUETASKTABLE`;
CREATE TABLE `QUEUETASKTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDATE` datetime DEFAULT NULL,
  `PROJECT` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `QUEUENAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `QUEUETASK` mediumblob,
  PRIMARY KEY (`ID`),
  KEY `idx_QUEUENAME` (`PROJECT`,`QUEUENAME`,`CREATEDATE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3372330 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for SPIDER_CRAWLINFOCACHETABLE
-- ----------------------------
DROP TABLE IF EXISTS `SPIDER_CRAWLINFOCACHETABLE`;
CREATE TABLE `SPIDER_CRAWLINFOCACHETABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRAWLDATAFORM` mediumblob,
  `CREATEDATE` datetime DEFAULT NULL,
  `READINFODIGEST` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for SPIDER_FILEDOWNLOADSTATUSTABLE
-- ----------------------------
DROP TABLE IF EXISTS `SPIDER_FILEDOWNLOADSTATUSTABLE`;
CREATE TABLE `SPIDER_FILEDOWNLOADSTATUSTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDATE` datetime DEFAULT NULL,
  `EXCEPTIONTIMES` int(11) DEFAULT NULL,
  `MESSAGE` varchar(800) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `ORIGINALFILE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `PERCENTAGE` double DEFAULT NULL,
  `RATE` int(11) DEFAULT NULL,
  `SITEID` bigint(20) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `STORAGELOCATION` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `TARGETFILE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=59008 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for STATISTICTABLE
-- ----------------------------
DROP TABLE IF EXISTS `STATISTICTABLE`;
CREATE TABLE `STATISTICTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COUNT` int(11) DEFAULT NULL,
  `REMARK` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `STATISTICTABLENAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `STATISTICTYPE` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for SYSTEMCONFIGTABLE
-- ----------------------------
DROP TABLE IF EXISTS `SYSTEMCONFIGTABLE`;
CREATE TABLE `SYSTEMCONFIGTABLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATEDATE` datetime DEFAULT NULL,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `PROJECT` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  `VALUE` mediumblob,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
